"""empty message

Revision ID: 0d7c2093283b
Revises: 
Create Date: 2024-10-28 22:11:29.094062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7c2093283b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_reto', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('dificultad', sa.String(length=255), nullable=True),
    sa.Column('lenguaje', sa.String(length=255), nullable=True),
    sa.Column('tests', sa.String(length=255), nullable=True),
    sa.Column('pistas', sa.String(length=255), nullable=True),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes')
    op.drop_table('usuarios')
    op.drop_table('retos')
    # ### end Alembic commands ###
